services:
  postgres:
    image: docker.io/postgres:17 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./test_data.sql:/docker-entrypoint-initdb.d/test_data.sql
